#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridlandMetro' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER m
#  3. INTEGER k
#  4. 2D_INTEGER_ARRAY track
#


from collections import defaultdict

def gridlandMetro(n, m, k, track):
    
    row_record = defaultdict(list)
    for r, c1, c2 in track:
        if r not in row_record:
            row_record[r] = [c1, c2]
        else:
            st, ed = row_record[r][0], row_record[r][1]
            if c1 > ed:
                row_record[r][1] += c2 - c1 + 1
            else:
                row_record[r][1] = max(ed, c2)
            if c2 < st:
                row_record[r][0] -= c2 - c1 + 1
            else:
                row_record[r][0] = min(st, c1)
            
    total_num = n * m
    for st, ed in row_record.values():
        total_num -= ed - st + 1
        
    return total_num

    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    k = int(first_multiple_input[2])

    track = []

    for _ in range(k):
        track.append(list(map(int, input().rstrip().split())))

    result = gridlandMetro(n, m, k, track)

    fptr.write(str(result) + '\n')

    fptr.close()
